#
# Web Server configuration
#
server:
  port: 8080
  host: 0.0.0.0
  worker-count: 8

#
# JDBC configuration
#
# Note: Takes precedence over dbclient section. Comment out to use dbclient below.
#
dataSource:
  jdbcUrl: "jdbc:postgresql://tfb-database:5432/hello_world"
  username: benchmarkdbuser
  password: benchmarkdbpass
  maximumPoolSize: 512

#
# DB Client configuration
#
# Note: Comment out the dataSource section to use DbClient
#
dbclient:
  source: "jdbc"
  connection:
    url: "jdbc:postgresql://tfb-database:5432/hello_world"
    username: "benchmarkdbuser"
    password: "benchmarkdbpass"
    maximumPoolSize: 512
  statements:
    get-world: "SELECT id, randomNumber FROM World WHERE id = ?"
    update-world: "UPDATE World SET randomNumber = ? WHERE id = ?"
    all-fortunes: "SELECT id, message FROM Fortune"
  executor-service:
    core-pool-size: 32
    max-pool-size: 32
    thread-name-prefix: "dbc-"
    should-prestart: true
